var PROJECT_TITLE="Ujnotes";function nowLoading(){var a=document.getElementById("loading");void 0===nowLoading.count?(nowLoading.count=0,resetLoadingText(a),a.setAttribute("style","visibility: visible")):3==nowLoading.count?resetLoadingText(a):(a.innerText+=".",nowLoading.count++)}function beginLoading(){clearTimeout(intrvl);intrvl=setInterval(nowLoading,1E3)}function resetLoadingText(a){a.innerText="Loading"}
function errorLoading(){var a=document.getElementById("loading");a.setAttribute("style","visibility: visible");a.innerText="Error!"}function killLoading(){var a=document.getElementById("loading");nowLoading.count=void 0;a.setAttribute("style","visibility: hidden");clearTimeout(intrvl)}function fbReload(){try{FB.XFBML.parse()}catch(a){}}
function getElementsByClassName(a,j){if(a.getElementsByClassName)return a.getElementsByClassName(j);var h=a;null==h&&(h=document);var g=[],h=h.getElementsByTagName("*"),t=h.length,l=RegExp("(^|\\s)"+j+"(\\s|$)"),v,c;for(c=v=0;v<t;v++)l.test(h[v].className)&&(g[c]=h[v],c++);return g}function supportsSvg(){var a=document.createElement("div");a.innerHTML="<svg/>";return"http://www.w3.org/2000/svg"==(a.firstChild&&a.firstChild.namespaceURI)}
"undefined"!==typeof document&&!("classList"in document.createElement("a"))&&function(a){a=(a.HTMLElement||a.Element).prototype;var j=Object,h=String.prototype.trim||function(){return this.replace(/^\s+|\s+$/g,"")},g=Array.prototype.indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(b in this&&this[b]===a)return b;return-1},t=function(a,b){this.name=a;this.code=DOMException[a];this.message=b},l=function(a,b){if(""===b)throw new t("SYNTAX_ERR","An invalid or illegal string was specified");if(/\s/.test(b))throw new t("INVALID_CHARACTER_ERR",
"String contains an invalid character");return g.call(a,b)},v=function(a){for(var b=h.call(a.className),b=b?b.split(/\s+/):[],c=0,g=b.length;c<g;c++)this.push(b[c]);this._updateClassName=function(){a.className=this.toString()}},c=v.prototype=[],b=function(){return new v(this)};t.prototype=Error.prototype;c.item=function(a){return this[a]||null};c.contains=function(a){return-1!==l(this,a+"")};c.add=function(a){a+="";-1===l(this,a)&&(this.push(a),this._updateClassName())};c.remove=function(a){a=l(this,
a+"");-1!==a&&(this.splice(a,1),this._updateClassName())};c.toggle=function(a){a+="";-1===l(this,a)?this.add(a):this.remove(a)};c.toString=function(){return this.join(" ")};if(j.defineProperty){c={get:b,enumerable:!0,configurable:!0};try{j.defineProperty(a,"classList",c)}catch(s){-2146823252===s.number&&(c.enumerable=!1,j.defineProperty(a,"classList",c))}}else j.prototype.__defineGetter__&&a.__defineGetter__("classList",b)}(self);
(function(a){function j(a,c){(h(a,c)?t:g)(a,c)}var h,g,t;"classList"in document.documentElement?(h=function(a,c){return a.classList.contains(c)},g=function(a,c){a.classList.add(c)},t=function(a,c){a.classList.remove(c)}):(h=function(a,c){return RegExp("(^|\\s+)"+c+"(\\s+|$)").test(a.className)},g=function(a,c){h(a,c)||(a.className=a.className+" "+c)},t=function(a,c){a.className=a.className.replace(RegExp("(^|\\s+)"+c+"(\\s+|$)")," ")});var l={hasClass:h,addClass:g,removeClass:t,toggleClass:j,has:h,
add:g,remove:t,toggle:j};"function"===typeof define&&define.amd?define(l):"object"===typeof exports?module.exports=l:a.classie=l})(window);
(function(a,j,h,g,t){var l=a.document,v=l.documentElement,c=a.history||{},b=a.location,s=!!c.pushState,Z=s&&c.state===t,x=b.href,w=a.JSON||{},C=Object.defineProperty,D=Object.prototype.__defineGetter__,$=Object.prototype.__defineSetter__,V=c.pushState,W=c.replaceState,I=a.sessionStorage,E=Object.prototype.hasOwnProperty,aa=Object.prototype.toString,J=+((a.eval&&eval("/*@cc_on 1;@*/")&&/msie (\d+)/i.exec(navigator.userAgent)||[])[1]||0),ba=(new Date).getTime(),y=(C||D)&&(!J||8<J)?0:1,m=8>J?l.createElement("iframe"):
h,z,F,G,H="",K=(z="addEventListener",a[z])||(z="attachEvent",H="on",a[z]),ca=(F="removeEventListener",a[F])||(F="detachEvent",a[F]),da=(G="dispatchEvent",a[G])||(G="fireEvent",a[G]),L=[],X=[],P=0,A={onpopstate:L,popstate:L,onhashchange:X,hashchange:X},u=function(){var f,a,b,e={basepath:"/",redirect:0,type:"/"};b=l.getElementsByTagName("SCRIPT");for(f=0;b[f];f++)if(a=/(.*)\/(?:history|spike)(?:-\d\.\d(?:\.\d)?\w?)?(?:\.min)?.js\?(.*)$/i.exec(b[f].src)||f===b.length-1&&2===(a=b[f].src.split("?")).length&&
(a[2]=a[1])&&a){f=0;for(b=a[2].split("&");b[f];)a=b[f++].split("="),e[a[0]]="true"==a[1]?j:"false"==a[1]?h:a[1]||"";e.basepath=e.basepath||"/";break}return e}(),p=function(a){var n,Q,e,d,B,k,c,ea=RegExp("^"+u.basepath,"i");return function(q,ha){if(q){if(!s||J){var g=p(),h=g._pathname,j=g._protocol;q=/^(?:[\w0-9]+\:)?\/\//.test(q)?0===q.indexOf("/")?j+q:q:j+"//"+g._host+(0===q.indexOf("/")?q:0===q.indexOf("?")?h+q:0===q.indexOf("#")?h+g._search+q:h.replace(/[^\/]+$/g,"")+q)}}else if(q=b.href,!s||ha)q=
b.protocol+"//"+b.host+u.basepath+(q.replace(/^[^#]*/,"")||"#").replace(RegExp("^#[/]?(?:"+u.type+")?"),"");if(n!==q){a.href=n=q;k=a.port;B=a.host;c=a.pathname;if("http:"===a.protocol&&80==k||"https:"===a.protocol&&443==k)B=a.hostname,k="";c=0===c.indexOf("/")?c:"/"+c;Q=c+a.search+a.hash;d=c.replace(ea,u.type)+a.search;e=d+a.hash}return{_href:a.protocol+"//"+B+Q,_protocol:a.protocol,_host:B,_hostname:a.hostname||b.hostname,_port:k||b.port,_pathname:c,_search:a.search,_hash:a.hash,_relative:Q,_nohash:d,
_special:e}}}(l.createElement("a")),r=!y?c:{back:c.back,forward:c.forward,go:c.go,pushState:g,replaceState:g,emulate:!s,toString:function(){return"[object History]"}},M={state:{get:function(){return m&&m.storage||R()[r.location.href]||g}},length:{get:function(){return c.length}},location:{set:function(f){a.location=f},get:function(){return s?b:S}}},S={assign:function(a){b.assign(s||0!==a.indexOf("#")?a:"#"+p()._nohash+a)},reload:b.reload,replace:function(a){b.replace(s||0!==a.indexOf("#")?a:"#"+p()._nohash+
a)},toString:function(){return this.href}},fa={href:{set:function(a){b.href=a},get:function(){return p()._href}},protocol:{set:function(a){b.protocol=a},get:function(){return b.protocol}},host:{set:function(a){b.host=a},get:function(){return b.host}},hostname:{set:function(a){b.hostname=a},get:function(){return b.hostname}},port:{set:function(a){b.port=a},get:function(){return b.port}},pathname:{set:function(a){b.pathname=a},get:function(){return p()._pathname}},search:{set:function(a){b.search=a},
get:function(){return p()._search}},hash:{set:function(a){a=0===a.indexOf("#")?a:"#"+a;var n=p();m?a!=n._hash&&(r.pushState(g,g,n._nohash+a),Y({oldURL:n._href})):b.hash="#"+n._nohash+a},get:function(){return p()._hash}}},T=function(f,n,b){var e=f,d,c=h;if(C||D)for(d in n){if(E.call(n,d))if(D)n[d].get&&D.call(f,d,n[d].get),n[d].set&&$.call(f,d,n[d].set);else if(C)try{C(f,d,n[d])}catch(k){if(b)return h;c=j;break}}else c=j;if(c&&y){b="StaticClass"+ba+y++;e=["Class "+b];"execVB"in a||execScript("Function execVB(c) ExecuteGlobal(c) End Function",
"VBScript");"VBCVal"in a||execScript("Function VBCVal(o,r) If IsObject(o) Then Set r=o Else r=o End If End Function","VBScript");for(d in f)e[e.length]="Public ["+d+"]";E.call(f,"toString")&&(f.propertyIsEnumerable("toString")||(e[e.length]="Public [toString]"),n["(toString)"]={get:function(){return this.toString.call(this)}});for(d in n)E.call(n,d)&&(n[d].get&&(f["get "+d]=n[d].get,e.push("Public [get "+d+"]","Public "+("(toString)"===d?"Default ":"")+"Property Get ["+d+"]","Call VBCVal(me.[get "+
d+"].call(me),["+d+"])","End Property")),n[d].set&&(f["set "+d]=n[d].set,e.push("Public [set "+d+"]","Public Property Let ["+d+"](v)","Call me.[set "+d+"].call(me,v)","End Property","Public Property Set ["+d+"](v)","Call me.[set "+d+"].call(me,v)","End Property")));e.push("End Class","Function "+b+"Factory()","Set "+b+"Factory=New "+b,"End Function");execVB(e.join("\n"));e=a[b+"Factory"]();for(d in f)e[d]=f[d];E.call(f,"toString")&&(e.toString=f.toString)}return e},N=w.stringify||function(a){function n(a){var f=
/[\\\"\u0000-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,b={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};f.lastIndex=0;return f.test(a)?'"'+a.replace(f,function(a){var f=b[a];return"string"===typeof f?f:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}var b=function(e){var d,c,k;d=(typeof e).charCodeAt(2);if(114===d)e=n(e);else if(109===d)e=isFinite(e)?String(e):"null";else if(111===
d||108===d)e=String(e);else if(106===d)if(e){c=(d="[object Array]"===aa.apply(e))?"[":"{";if(d)for(k=0;k<e.length;k++)c+=(0==k?"":",")+b(e[k]);else for(k in e)E.call(e,k)&&e[k]!==a&&(c+=(1==c.length?"":",")+n(k)+":"+b(e[k]));e=c+(d?"]":"}")}else e="null";else e=a;return e};return b}(),U=function(){var a=w.parse;return function(b){return b?a?a(b):(new Function("return "+b))():g}}(),R=function(a){return I?a?I.setItem("__hitoryapi__",N(a)):U(I.getItem("__hitoryapi__"))||{}:{}},O=function(f,b,c){var e=
2===f?a.onhashchange:a.onpopstate,d=2===f?"hashchange":"popstate",g=A[d];l.createEvent?(f=l.createEvent("Events"),f.initEvent(d,h,h)):(f=l.createEventObject(),f.type=d);f.state=r.state;f.oldURL=b;f.newURL=c;e&&e.call(a,f);b=0;for(c=g.length;b<c;b++)g[b].call(a,f)},Y=function(){var f=a.onpopstate||g,n=a.onhashchange||g,Q=0,e=g,d=p(),B=d._href;d._hash.replace(/^#/,"");var k=function(){if(x&&!(x=0)&&d._relative!==u.basepath)clearInterval(e),setTimeout(O,10)},m=function(a){var f=p();if(P)return B=f._href,
P=0;var d=a.oldURL||B;a=B=a.newURL||f._href;var f=d.replace(/^.*?(#|$)/,""),b=a.replace(/^.*?(#|$)/,"");d!=a&&!Q&&O();x=Q=0;f!=b&&O(2,d,a)};K(H+"hashchange",m,h);K(H+"popstate",function(){if(x===b.href)return x=0;x=0;O(Q=1)},h);r.redirect=function(f,d){u.type=f===t?u.type:f;u.basepath=d===t?u.basepath:d;if(a.top==a.self){var e=p(g,j)._relative,n=b.search,c=b.pathname;d=u.basepath;s?(e!=d&&RegExp("^"+d+"$","i").test(c)&&(b.href=e),RegExp("^"+d+"$","i").test(c+"/")?b.href=d:RegExp("^"+d,"i").test(c)||
(b.href=c.replace(/^\//,d)+n)):c!=d&&(b.href=d+"#"+c.replace(RegExp("^"+d,"i"),u.type)+n+b.hash)}};r=T(r,y?M:c.state===t?{state:M.state,location:M.location}:{location:M.location});S=T(S,fa);a[z]=function(a,f,d,b){A[a]?(A[a].push(f),!s&&L===A[a]&&k()):K(a,f,d,b)};a[F]=function(a,f,d){var b=A[a];if(b)for(a=b.length;--a;){if(b[a]===f){b.splice(a,1);break}}else ca(a,f,d)};a[G]=function(f,d){var b=A[f],e=b===L?a.onpopstate:a.onhashchange;if(b){d=d||("string"==typeof f?a.event:f);try{d&&(d.target=a)}catch(n){try{d.srcElement=
a}catch(c){}}e&&e.call(a,d);for(var e=0,k=b.length;e<k;e++)b[e].call(a,d);return j}return da(f,d)};y&&execScript("Public history, onhashchange","VBScript");if((!C&&!D||!T(a,{onhashchange:{get:function(){return n},set:function(a){n=a||g}},onpopstate:{get:function(){return f},set:function(a){(f=a||g)&&!s&&k()}}},1))&&!s)e=setInterval(function(){a.onpopstate&&k()},100);u.redirect&&r.redirect();if(!s)l[z](H+"click",function(f){var d=f||a.event,b=d.target||d.srcElement;f="defaultPrevented"in d?d.defaultPrevented:
d.returnValue===h;if(b&&("A"===b.nodeName&&!f)&&(f=p(b.getAttribute("href",2),j),f._hash&&"#"!==f._hash&&f._hash===f._href.replace(p()._href.split("#").shift(),""))){history.location.hash=f._hash;f=f._hash.replace(/^#/,"");if((b=l.getElementById(f))&&b.id===f&&"A"===b.nodeName)b=b.getBoundingClientRect(),a.scrollTo(v.scrollLeft||0,b.top+(v.scrollTop||0)-(v.clientTop||0));d.preventDefault?d.preventDefault():d.returnValue=!1}},h);return m}();r.pushState=function(a,n,c,e){var d=R(),h=p()._href,k=c&&
p(c);x=0;c=k?k._href:h;e&&d[h]&&delete d[h];if((!s||Z)&&I&&a)d[c]=a,R(d),a=g;V&&W?e?W.call(r,a,n,c):V.call(r,a,n,c):k&&k._relative!=p()._relative&&(P=1,e?b.replace("#"+k._special):b.hash=k._special)};r.replaceState=function(a,b,c){r.pushState(a,b,c,1)};y?(a.history=r,function(f,n){if(m){var c,e,d=function(){var a=p()._href;n!=a&&Y({oldURL:n,newURL:n=a})};e=setInterval(d,100);m.src="javascript:true;";m=v.firstChild.appendChild(m).contentWindow;r.pushState=c=function(a,f,g,q,h){var j=m.document,l=["<script>",
"lfirst=1;",,"storage="+N(a)+";","\x3c/script>"];if(g=g&&p(g)){h||clearInterval(e);if(q)m.lfirst?(history.back(),c(a,f,g._href,0,1)):(m.storage=a,b.replace("#"+g._special));else if(g._href!=n||h)m.lfirst||(m.lfirst=1,c(m.storage,f,n,0,1)),l[2]='parent.location.hash="'+g._special.replace(/"/g,'\\"')+'";',j.open(),j.write(l.join("")),j.close();h||(n=p()._href,e=setInterval(d,100))}else m.storage=a};K(H+"unload",function(){if(m.storage){var a={};a[p()._href]=m.storage;l.cookie="_historyAPI="+escape(N(a))}clearInterval(e)},
h);if(1<f.length){f=unescape(f.pop().split(";").shift());try{m.storage=U(f)[p()._href]}catch(g){}}!w.parse&&!w.stringify&&(w.parse=U,w.stringify=N,a.JSON=w)}}(l.cookie.split("_historyAPI="),p()._href)):a.history.emulate=!s})(window,!0,!1,null);var curTab,intrvl=0,gTarget,URLid;window.onload=Init;var trackOutboundLink=function(a,j){"undefined"!==typeof ga&&("undefined"!==typeof a&&(a=j),ga("send","event","outbound","click",a,{transport:"beacon",hitCallback:function(){document.location=j}}))};
window.onpopstate=function(a){a.state&&("menu"==a.state.id?activateMenuFn():(LoadCanvas(a.state.id,a.state.title),activateMainFn()))};var menuActive=!1;
function Init(){SetXURL(document);var a=GetHashID();URLid=GetURLid();var j=document.querySelector("#canvas-main"),h=document.querySelector(".toggle-push-left"),g=document.querySelectorAll(".XURL");a?(curTab="root",LoadCanvas(document.getElementById(a))):curTab=URLid?URLid:"root";"menu"==URLid?(menuActive=!0,classie.add(h,"active"),j.style.maxHeight=document.querySelector("#nav-menu").scrollHeight+"px"):document.querySelector("#nav-menu").style.maxHeight=j.scrollHeight+"px";!a&&!URLid&&window.history.replaceState({id:"root"},
"","/");h.addEventListener("click",function(){if(menuActive){if("root"==curTab||"menu"==curTab)curTab="";window.history.pushState({id:curTab},"","/"+curTab);activateMainFn();j.style.maxHeight="99999px";document.querySelector("#nav-menu").style.maxHeight=j.scrollHeight+"px";document.getElementById("path").style.visibility="visible";document.getElementById("title").style.visibility="visible";document.getElementById("updated").style.visibility="visible"}else activateMenuFn()});[].forEach.call(document.getElementsByClassName("coming-soon"),
function(a){a.addEventListener("click",function(){"undefined"!==typeof ga&&ga("send","event",{eventCategory:"download",eventAction:"click"});alert("Hold your breath! Coming soon..")})});[].slice.call(g).forEach(function(a){a.addEventListener("click",function(){curTab=this.getAttribute("data-target");activateMainFn()})});if(!supportsSvg()){a=document.getElementsByClassName("image");g=a.length;for(h=0;h<g;h++)a[h].classList.add("no-svg")}initPageFunction(curTab);return!1}
var initPageFunction=function(a){a=a.replace("/","__");if("function"===typeof window[a])window[a]()},activateMenuFn=function(){document.getElementById("path").style.visibility="hidden";document.getElementById("title").style.visibility="hidden";document.getElementById("updated").style.visibility="hidden";var a=document.querySelector("#nav-menu"),j=document.querySelector("#canvas-main"),h=document.querySelector("#canvas-wrapper"),g=document.querySelector("#menu-button");window.history.pushState({id:"menu"},
"","/menu");classie.add(h,"pml-open");classie.add(g,"active");activeNav="pml-open";j.style.maxHeight=a.scrollHeight+"px";a.style.maxHeight="99999px";menuActive=!0;"undefined"!==typeof ga&&(ga("set","page","/menu"),ga("send","pageview"))},activateMainFn=function(){document.querySelector("#nav-menu");var a=document.querySelector("#canvas-wrapper"),j=document.querySelector("#menu-button");classie.remove(a,"pml-open");classie.remove(j,"active");menuActive=!1};
function GetURLid(){var a=window.location.pathname;return"/"==a?"":a.substring(1)}function GetHashID(){var a=window.location.hash;return 0==a.length?"":a.substring(2)}function SetXURL(a){a=getElementsByClassName(a,"XURL");var j=a.length;for(i=0;i<j;i++)a[i].onclick=LoadCanvasI}function LoadCanvasI(){LoadCanvasH(this);return!1}
function LoadCanvasH(a){var j=a.getAttribute("data-target");URLid="root"==j?"":j;LoadCanvas(j,a.getAttribute("data-title"));window.history.pushState({id:j,title:a.getAttribute("data-title")},"","/"+URLid);"undefined"!==typeof ga&&(ga("set","page","/"+URLid),ga("send","pageview"))}
function LoadCanvas(a,j){"root"==a&&(document.getElementById("path").style.visibility="hidden",document.getElementById("title").style.visibility="hidden");var h=document.getElementById("updated");document.getElementById("canvas-main").innerHTML="";h.style.visibility="hidden";beginLoading();var g=new XMLHttpRequest,g=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");g.onreadystatechange=function(){if(4==g.readyState&&a===gTarget){var t=document.getElementById("canvas-main");
switch(g.status){case 200:killLoading();var l=JSON.parse(g.responseText),v=l.xurl,c=l.async,b=PROJECT_TITLE;"root"!=a&&(b+=" - "+j);b+=" : "+l.desc;document.title=b;"root"==a?(document.getElementById("path").innerHTML="&nbsp;",document.getElementById("title").innerHTML=""):(document.getElementById("path").innerHTML=l.path,document.getElementById("title").innerHTML=j);t.innerHTML=l.content;document.getElementById("updated").style.display="block";document.getElementById("date").innerHTML=l.date;""==
!URLid&&(document.getElementById("path").style.visibility="visible",document.getElementById("title").style.visibility="visible");document.getElementById("updated").style.visibility="visible";t=document.getElementById("canvas-main").scrollHeight;document.getElementById("nav-menu").style.maxHeight=t+"px";document.getElementById("canvas-main").style.maxHeight="99999px";h.style.visibility="visible";"1"==v&&SetXURL(document);"1"==c&&initPageFunction(a);fbReload();break;case 404:document.getElementById("updated").style.display=
"none";document.getElementById("date").innerHTML="";t.innerHTML="Error: 404 - Resource not found!";break;case 408:case 501:case 502:document.getElementById("date").innerHTML="",document.getElementById("updated").style.display="none",t.innerHTML="Error!",errorLoading()}}};gTarget=a;g.open("GET","/"+a+".json",!0);g.setRequestHeader("Content-Type","text/plain;charset=UTF-8");g.send()}
(!window.history||!window.history.pushState)&&function(a,j,h,g,t){var l=a.document,v=l.documentElement,c=a.history||{},b=a.location,s=!!c.pushState,Z=s&&c.state===t,x=b.href,w=a.JSON||{},C=Object.defineProperty,D=Object.prototype.__defineGetter__,$=Object.prototype.__defineSetter__,V=c.pushState,W=c.replaceState,I=a.sessionStorage,E=Object.prototype.hasOwnProperty,aa=Object.prototype.toString,J=+((a.eval&&eval("/*@cc_on 1;@*/")&&/msie (\d+)/i.exec(navigator.userAgent)||[])[1]||0),ba=(new Date).getTime(),
y=(C||D)&&(!J||8<J)?0:1,m=8>J?l.createElement("iframe"):h,z,F,G,H="",K=(z="addEventListener",a[z])||(z="attachEvent",H="on",a[z]),ca=(F="removeEventListener",a[F])||(F="detachEvent",a[F]),da=(G="dispatchEvent",a[G])||(G="fireEvent",a[G]),L=[],X=[],P=0,A={onpopstate:L,popstate:L,onhashchange:X,hashchange:X},u=function(){var a,b,c,e={basepath:"/",redirect:0,type:"/"};c=l.getElementsByTagName("SCRIPT");for(a=0;c[a];a++)if(b=/(.*)\/(?:history|spike)(?:-\d\.\d(?:\.\d)?\w?)?(?:\.min)?.js\?(.*)$/i.exec(c[a].src)||
a===c.length-1&&2===(b=c[a].src.split("?")).length&&(b[2]=b[1])&&b){a=0;for(c=b[2].split("&");c[a];)b=c[a++].split("="),e[b[0]]="true"==b[1]?j:"false"==b[1]?h:b[1]||"";e.basepath=e.basepath||"/";break}return e}(),p=function(a){var c,g,e,d,h,k,j,ea=RegExp("^"+u.basepath,"i");return function(q,l){if(q){if(!s||J){var m=p(),r=m._pathname,t=m._protocol;q=/^(?:[\w0-9]+\:)?\/\//.test(q)?0===q.indexOf("/")?t+q:q:t+"//"+m._host+(0===q.indexOf("/")?q:0===q.indexOf("?")?r+q:0===q.indexOf("#")?r+m._search+q:
r.replace(/[^\/]+$/g,"")+q)}}else if(q=b.href,!s||l)q=b.protocol+"//"+b.host+u.basepath+(q.replace(/^[^#]*/,"")||"#").replace(RegExp("^#[/]?(?:"+u.type+")?"),"");if(c!==q){a.href=c=q;k=a.port;h=a.host;j=a.pathname;if("http:"===a.protocol&&80==k||"https:"===a.protocol&&443==k)h=a.hostname,k="";j=0===j.indexOf("/")?j:"/"+j;g=j+a.search+a.hash;d=j.replace(ea,u.type)+a.search;e=d+a.hash}return{_href:a.protocol+"//"+h+g,_protocol:a.protocol,_host:h,_hostname:a.hostname||b.hostname,_port:k||b.port,_pathname:j,
_search:a.search,_hash:a.hash,_relative:g,_nohash:d,_special:e}}}(l.createElement("a")),r=!y?c:{back:c.back,forward:c.forward,go:c.go,pushState:g,replaceState:g,emulate:!s,toString:function(){return"[object History]"}},M={state:{get:function(){return m&&m.storage||R()[r.location.href]||g}},length:{get:function(){return c.length}},location:{set:function(f){a.location=f},get:function(){return s?b:S}}},S={assign:function(a){b.assign(s||0!==a.indexOf("#")?a:"#"+p()._nohash+a)},reload:b.reload,replace:function(a){b.replace(s||
0!==a.indexOf("#")?a:"#"+p()._nohash+a)},toString:function(){return this.href}},fa={href:{set:function(a){b.href=a},get:function(){return p()._href}},protocol:{set:function(a){b.protocol=a},get:function(){return b.protocol}},host:{set:function(a){b.host=a},get:function(){return b.host}},hostname:{set:function(a){b.hostname=a},get:function(){return b.hostname}},port:{set:function(a){b.port=a},get:function(){return b.port}},pathname:{set:function(a){b.pathname=a},get:function(){return p()._pathname}},
search:{set:function(a){b.search=a},get:function(){return p()._search}},hash:{set:function(a){a=0===a.indexOf("#")?a:"#"+a;var c=p();m?a!=c._hash&&(r.pushState(g,g,c._nohash+a),Y({oldURL:c._href})):b.hash="#"+c._nohash+a},get:function(){return p()._hash}}},T=function(b,c,g){var e=b,d,l=h;if(C||D)for(d in c){if(E.call(c,d))if(D)c[d].get&&D.call(b,d,c[d].get),c[d].set&&$.call(b,d,c[d].set);else if(C)try{C(b,d,c[d])}catch(k){if(g)return h;l=j;break}}else l=j;if(l&&y){g="StaticClass"+ba+y++;e=["Class "+
g];"execVB"in a||execScript("Function execVB(c) ExecuteGlobal(c) End Function","VBScript");"VBCVal"in a||execScript("Function VBCVal(o,r) If IsObject(o) Then Set r=o Else r=o End If End Function","VBScript");for(d in b)e[e.length]="Public ["+d+"]";E.call(b,"toString")&&(b.propertyIsEnumerable("toString")||(e[e.length]="Public [toString]"),c["(toString)"]={get:function(){return this.toString.call(this)}});for(d in c)E.call(c,d)&&(c[d].get&&(b["get "+d]=c[d].get,e.push("Public [get "+d+"]","Public "+
("(toString)"===d?"Default ":"")+"Property Get ["+d+"]","Call VBCVal(me.[get "+d+"].call(me),["+d+"])","End Property")),c[d].set&&(b["set "+d]=c[d].set,e.push("Public [set "+d+"]","Public Property Let ["+d+"](v)","Call me.[set "+d+"].call(me,v)","End Property","Public Property Set ["+d+"](v)","Call me.[set "+d+"].call(me,v)","End Property")));e.push("End Class","Function "+g+"Factory()","Set "+g+"Factory=New "+g,"End Function");execVB(e.join("\n"));e=a[g+"Factory"]();for(d in b)e[d]=b[d];E.call(b,
"toString")&&(e.toString=b.toString)}return e},N=w.stringify||function(a){function b(a){var d=/[\\\"\u0000-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,c={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};d.lastIndex=0;return d.test(a)?'"'+a.replace(d,function(a){var b=c[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}var c=function(e){var d,g,k;
d=(typeof e).charCodeAt(2);if(114===d)e=b(e);else if(109===d)e=isFinite(e)?String(e):"null";else if(111===d||108===d)e=String(e);else if(106===d)if(e){g=(d="[object Array]"===aa.apply(e))?"[":"{";if(d)for(k=0;k<e.length;k++)g+=(0==k?"":",")+c(e[k]);else for(k in e)E.call(e,k)&&e[k]!==a&&(g+=(1==g.length?"":",")+b(k)+":"+c(e[k]));e=g+(d?"]":"}")}else e="null";else e=a;return e};return c}(),U=function(){var a=w.parse;return function(b){return b?a?a(b):(new Function("return "+b))():g}}(),R=function(a){return I?
a?I.setItem("__hitoryapi__",N(a)):U(I.getItem("__hitoryapi__"))||{}:{}},O=function(b,c,g){var e=2===b?a.onhashchange:a.onpopstate,d=2===b?"hashchange":"popstate",j=A[d];l.createEvent?(b=l.createEvent("Events"),b.initEvent(d,h,h)):(b=l.createEventObject(),b.type=d);b.state=r.state;b.oldURL=c;b.newURL=g;e&&e.call(a,b);c=0;for(g=j.length;c<g;c++)j[c].call(a,b)},Y=function(){var f=a.onpopstate||g,n=a.onhashchange||g,m=0,e=g,d=p(),B=d._href;d._hash.replace(/^#/,"");var k=function(){if(x&&!(x=0)&&d._relative!==
u.basepath)clearInterval(e),setTimeout(O,10)},w=function(a){var b=p();if(P)return B=b._href,P=0;var d=a.oldURL||B;a=B=a.newURL||b._href;var b=d.replace(/^.*?(#|$)/,""),c=a.replace(/^.*?(#|$)/,"");d!=a&&!m&&O();x=m=0;b!=c&&O(2,d,a)};K(H+"hashchange",w,h);K(H+"popstate",function(){if(x===b.href)return x=0;x=0;O(m=1)},h);r.redirect=function(d,c){u.type=d===t?u.type:d;u.basepath=c===t?u.basepath:c;if(a.top==a.self){var e=p(g,j)._relative,f=b.search,k=b.pathname;c=u.basepath;s?(e!=c&&RegExp("^"+c+"$",
"i").test(k)&&(b.href=e),RegExp("^"+c+"$","i").test(k+"/")?b.href=c:RegExp("^"+c,"i").test(k)||(b.href=k.replace(/^\//,c)+f)):k!=c&&(b.href=c+"#"+k.replace(RegExp("^"+c,"i"),u.type)+f+b.hash)}};r=T(r,y?M:c.state===t?{state:M.state,location:M.location}:{location:M.location});S=T(S,fa);a[z]=function(a,b,d,c){A[a]?(A[a].push(b),!s&&L===A[a]&&k()):K(a,b,d,c)};a[F]=function(a,b,d){var c=A[a];if(c)for(a=c.length;--a;){if(c[a]===b){c.splice(a,1);break}}else ca(a,b,d)};a[G]=function(b,d){var c=A[b],e=c===
L?a.onpopstate:a.onhashchange;if(c){d=d||("string"==typeof b?a.event:b);try{d&&(d.target=a)}catch(f){try{d.srcElement=a}catch(g){}}e&&e.call(a,d);for(var e=0,k=c.length;e<k;e++)c[e].call(a,d);return j}return da(b,d)};y&&execScript("Public history, onhashchange","VBScript");if((!C&&!D||!T(a,{onhashchange:{get:function(){return n},set:function(a){n=a||g}},onpopstate:{get:function(){return f},set:function(a){(f=a||g)&&!s&&k()}}},1))&&!s)e=setInterval(function(){a.onpopstate&&k()},100);u.redirect&&r.redirect();
if(!s)l[z](H+"click",function(b){var d=b||a.event,c=d.target||d.srcElement;b="defaultPrevented"in d?d.defaultPrevented:d.returnValue===h;if(c&&("A"===c.nodeName&&!b)&&(b=p(c.getAttribute("href",2),j),b._hash&&"#"!==b._hash&&b._hash===b._href.replace(p()._href.split("#").shift(),""))){history.location.hash=b._hash;b=b._hash.replace(/^#/,"");if((c=l.getElementById(b))&&c.id===b&&"A"===c.nodeName)c=c.getBoundingClientRect(),a.scrollTo(v.scrollLeft||0,c.top+(v.scrollTop||0)-(v.clientTop||0));d.preventDefault?
d.preventDefault():d.returnValue=!1}},h);return w}();r.pushState=function(a,c,h,e){var d=R(),j=p()._href,k=h&&p(h);x=0;h=k?k._href:j;e&&d[j]&&delete d[j];if((!s||Z)&&I&&a)d[h]=a,R(d),a=g;V&&W?e?W.call(r,a,c,h):V.call(r,a,c,h):k&&k._relative!=p()._relative&&(P=1,e?b.replace("#"+k._special):b.hash=k._special)};r.replaceState=function(a,b,c){r.pushState(a,b,c,1)};y?(a.history=r,function(c,g){if(m){var j,e,d=function(){var a=p()._href;g!=a&&Y({oldURL:g,newURL:g=a})};e=setInterval(d,100);m.src="javascript:true;";
m=v.firstChild.appendChild(m).contentWindow;r.pushState=j=function(a,c,f,h,l){var r=m.document,s=["<script>","lfirst=1;",,"storage="+N(a)+";","\x3c/script>"];if(f=f&&p(f)){l||clearInterval(e);if(h)m.lfirst?(history.back(),j(a,c,f._href,0,1)):(m.storage=a,b.replace("#"+f._special));else if(f._href!=g||l)m.lfirst||(m.lfirst=1,j(m.storage,c,g,0,1)),s[2]='parent.location.hash="'+f._special.replace(/"/g,'\\"')+'";',r.open(),r.write(s.join("")),r.close();l||(g=p()._href,e=setInterval(d,100))}else m.storage=
a};K(H+"unload",function(){if(m.storage){var a={};a[p()._href]=m.storage;l.cookie="_historyAPI="+escape(N(a))}clearInterval(e)},h);if(1<c.length){c=unescape(c.pop().split(";").shift());try{m.storage=U(c)[p()._href]}catch(s){}}!w.parse&&!w.stringify&&(w.parse=U,w.stringify=N,a.JSON=w)}}(l.cookie.split("_historyAPI="),p()._href)):a.history.emulate=!s}(window,!0,!1,null);
function root(){var a=document.getElementById("profile-image");root.full=!1;a.addEventListener("click",function(){root.full?(a.blur(),root.full=!1):root.full=!0})}function about_me(){gapi.plus.go("me_g-plus");twttr.widgets.load()}function presentation(){beginLoading()};
